### ISSUE TITLE
Missing dicebear icons since 10/30

### ISSUE THREAD

**Issue by NathanielRMoss** [KoyNetwork/open-block-explorer#26]
Dicebear icons have disappeared from stagenet and mainnet OBE. 

The gitaction deploys just fine.
The hyperion command returns just fine when run by hand.
It's not the chain itself, because I restarted it and it still hadn't shown up.
I certbot renewed, but the cert was good until 2024
and also it's on two separate machines and happened at about the same time.

SSL could be an issue, we saw a strange error, bur it doesn't happen all the time. That IP is mine. 
2023/10/31 15:11:45 [error] 1052#1052: *2103 connect() failed (111: Unknown error) while connecting to upstream, client: 98.232.91.231, server: hyptest.koy.network, request: "GET /v2/history/get_actions?sort=desc&limit=20 HTTP/1.1", upstream: "http://0.0.0.0:7001/v2/history/get_actions?sort=desc&limit=20", host: "hyptest.koy.network", referrer: "https://test-explore.koy.network/"

Could dicebear be looking somewhere that is not valid or is blocked?

VueJS store is `undefined` in the stagenet environment. This explains why headblock, dicebear, account information are all not showing up.

**Comment by DouglasHorn** [comment]
I noticed that the code seems to both build its own dicebear implementation and also call from the dicebear API. Is that correct? If so, it could explain why it works correctly on the local machine but not over the web.

**Comment by karynemayer** [comment]
The dicebear implementation relies on the JS library implementation, so we're solely relying on the `@dicebear/core` package and the packages that represent both used styles. It is all being concetrated in `store/profiles/actions`

**Comment by karynemayer** [comment]
This was caused by building the project with node version != 16.x.x
